name: Chromatic
on:
  push: { branches: [core, main] }
  pull_request:

jobs:
  chromatic:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with: { version: 9 }
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm
      - run: pnpm i --frozen-lockfile

      # (optional) run your Storybook Test Runner first:
      # - run: pnpm storybook -- --ci --port 6006 &
      # - run: npx wait-on http://localhost:6006
      # - run: pnpm test-storybook --url http://localhost:6006

      - name: Publish to Chromatic
        uses: chromaui/action@v11
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          # uncomment if your SB build script has a custom name:
          # buildScriptName: build-storybook
